nationalarchives/tna-judgments-parser

TRE/DockerfileV2
Trial Docker file for building in TRE/V2
=> DTE-828 Automate parser deploy for TRE V2

src/model/Citations.cs, src/model/Courts.cs, src/model2/Metadata.cs, src/parsers/coa/NeutralCitation.cs, test/judgments/test81.xml, test/judgments/test85.xml, test/judgments/test86.xml, version.targets
This adds support for EWCOP "tier" NCNs, e.g., [2024] EWCOP 30 (T2)
=> FCL-120 EWCOP tiers

src/docx/Numbering2.cs, src/model2/Line.cs, version.targets
This adds support for the number format %1-%2-%3-%4, needed for [2024] EWFC 163 (B). See Jira issue CLP-11879
=> CLP-11879 number format %1-%2-%3-%4

src/docx/Numbering2.cs
Check for XML attribute without throwing a KeyNotFoundException
=> quiet check for cached number

src/parsers/optimized/UKUT.cs, version.targets
Recognize "Decision Notice" as the title of a decision, as in [2024] UKFTT 721 (GRC)
=> CLP-12559 'Decision Notice' doc title

src/model/Citations.cs, src/model/Courts.cs, src/parsers/coa/NeutralCitation.cs, src/parsers/common/enrich/CourtType.cs, version.targets
add support for the Crown Court and the EWCR NCN format
=> FCL-258 add the Crown Court

src/parsers/optimized/UKUT.cs, src/parsers/ukut/JudgeNames.cs, test/judgments/test51.xml, version.targets
This fix identifies and annotates judge names in tribunal decisions
=> FCL-260 tribunal judge names

src/docx/Numbering2.cs, version.targets
This little fix ignores bullets whose text is the xf020 character
=> CLP-13156 remove bullets

src/akn/Builder.cs, src/akn/Metadata.cs, src/model/CaseName.cs, src/model/Inline.cs, src/model/Party.cs, src/model2/Inline.cs, src/model2/Line.cs, src/parsers/common/enrich/Party.cs, test/judgments/test31.xml, test/judgments/test32.xml, test/judgments/test6.xml, test/judgments/test8.xml, version.targets
This fix improves the handling of judicial review cases, in which technically the monarch brings the case on behalf of a party
=> improve parties with 'R on the application of' (FCL-274)

src/model/Util.cs, version.targets
=> images in annex headings

src/parsers/optimized/ps/Metadata.cs, version.targets
This fix improves the generation of case names in Press Summaries
=> Compound roles in SC case headings

.github/workflows/run_integration_tests.yml
=> Add run_integration_test.yml

.github/depenadbot.yml
Configure dependabot for dotnet
=> Configure dependabot for dotnet

backlog/Properties/AssemblyInfo.cs, backlog/src/Bundle.cs, backlog/src/batch/one/Helper.cs, test/backlog/TestBundle.cs
Add support for custom metadata fields like headnotes (courtesy of @jurisdatum )
Add tests for bundle code
=> Add support for custom metadata fields like headnotes

backlog/README.md, backlog/src/batch/one/Metadata.cs, test/backlog/TestHelperFindLines.cs, test/backlog/TestMetadata.cs
- Remove unused line properties
- Added csv file validation
- add helper findlines tests
- improve readme
=> Add csv column validation, tidy up and tests

backlog/README.md, backlog/src/batch/one/Metadata.cs, test/backlog/TestHelperFindLines.cs, test/backlog/TestMetadata.cs, test/backlog/expected-output/Money Worries Ltd v Office of Fair Trading.xml, test/backlog/test-data/Altaf Ebrahim t_a Ebrahim & Co v OISC/court_metadata.csv, test/backlog/test-data/Money Worries Ltd v Office of Fair Trading/court_metadata.csv
Add proper support for categories and sub categories.
Specifically, we have optional fields for categories and subcategories.
We have custom csv validation to ensure if subcategory is provided, category needs to exist
=> Add proper support for categories and sub categories

backlog/README.md, backlog/src/batch/one/Metadata.cs, test/backlog/TestHelperFindLines.cs, test/backlog/TestMetadata.cs, test/backlog/expected-output/Money Worries Ltd v Office of Fair Trading.xml, test/backlog/test-data/Altaf Ebrahim t_a Ebrahim & Co v OISC/court_metadata.csv, test/backlog/test-data/Money Worries Ltd v Office of Fair Trading/court_metadata.csv
Require CaseNo column, rather than separate constituent number columns
=> Require CaseNo column, rather than separate constituent number columns

backlog/src/batch/one/Metadata.cs, test/backlog/TestMetadata.cs
Handle appellants or claimants as FirstParty
=> Handle appellants or claimants as FirstParty

src/model/Courts.cs
=> Added FTT-Claims court

src/model/Courts.cs
Expose FTT-Claims court on Court class
=> Expose FTT-Claims court on Court class

test/backlog/EndToEndTests.cs
- reuse Tests.RemoveSomeMetadata so actual/expected XML comparisons ignore known volatile fields, including `<uk:parser>`
- test that parser version in generated XML matches the parser assembly’s informational version
- keep the old timestamp normaliser marked [Obsolete] and document the new helpers with summary comments
=> Revise backlog E2E tests so they don't depend on parser version
